title: The Thursday Lady
description: literary works by karla fc holloway
url: "https://thethursdaylady.com"
baseurl: ""

author:
  name: Justice Courtland

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md