title: The Thursday Lady
description: literary works by karla fc holloway
url: "https://escambron.github.io"
baseurl: "/the-thursday-lady"
url: "https://thethursdaylady.com"
baseurl: ""

author:
  name: karla fc holloway

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md